## Introduction to NumPy

### Installation of NumPy

In [1]:
import numpy
numpy.version.version

'1.20.1'

### Python Lists vs NumPy Arrays

In [2]:
numbers = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numbers

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
%timeit ones = [float(x) for x in range(1000)]

116 µs ± 4.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
%timeit ones = [1.] * 1000

2.78 µs ± 60.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
import numpy as np
%timeit ones = np.ones(1000, dtype=int)

2.58 µs ± 54.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Creating NumPy Arrays

In [6]:
myarray = np.array([1, 2, 3, 4, 5])
myarray

array([1, 2, 3, 4, 5])

In [7]:
myarray = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
myarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
myarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
myarray = np.array([[0, 1], [0.5, 1.5]])
myarray

array([[0. , 1. ],
       [0.5, 1.5]])

In [10]:
myarray = np.array([[0, 1], [0.5, 1.5]], dtype=int)
myarray

array([[0, 1],
       [0, 1]])

### Useful Functions for Making Arrays

In [11]:
myarray = np.arange(1, 11)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
myarray = np.arange(1, 11, 2)
myarray

array([1, 3, 5, 7, 9])

In [13]:
myarray = np.arange(100, 0, -10)
myarray

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [14]:
myarray = np.arange(1, 10).reshape(3, 3)
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
myarray = np.linspace(1, 10, 10)
myarray

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
myarray = np.linspace(0, 1, 5)
myarray

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Indexing and Slicing

In [17]:
myarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
myarray[1, 2]

7

In [18]:
myarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
myarray[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
myarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
myarray[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [20]:
myarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
myarray[myarray > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

## Introduction to Pandas

### Installation of Pandas

In [21]:
import pandas
pandas.__version__

'1.2.4'

### Creating DataFrames

In [22]:
import pandas as pd
name = pd.Series(["John", "Mary", "Peter", "Jane"], name="Name")
name

0     John
1     Mary
2    Peter
3     Jane
Name: Name, dtype: object

In [23]:
name = pd.Series(["John", "Mary", "Peter", "Jane"], name="Name")
year = pd.Series([1, 2, 1, 3], name="Year")
prog = pd.Series(["Computer Science",
                  "Mathematics",
                  "Finance",
                  "English"], name="Program")
table = pd.concat([name, year, prog], axis=1)
table

Name  Year           Program
0   John     1  Computer Science
1   Mary     2       Mathematics
2  Peter     1           Finance
3   Jane     3           English

In [24]:
table = pd.DataFrame({
    "Name": ["John", "Mary", "Peter", "Jane"],
    "Year": [1, 2, 1, 3],
    "Program": ["Computer Science",
                "Mathematics",
                "Finance",
                "English"]})
table

Name  Year           Program
0   John     1  Computer Science
1   Mary     2       Mathematics
2  Peter     1           Finance
3   Jane     3           English

### Reading Data into DataFrames

In [25]:
table = pd.read_csv("students.csv")
table

Name  Year           Program
0   John     1  Computer Science
1   Mary     2       Mathematics
2  Peter     1           Finance
3   Jane     3           English

### Indexing and Slicing

In [26]:
table.at[2, "Program"]

'Finance'

In [27]:
table.loc[1:2, "Name":"Program"]

Name  Year      Program
1   Mary     2  Mathematics
2  Peter     1      Finance

In [28]:
table.loc[1:2, ["Name", "Program"]]

Name      Program
1   Mary  Mathematics
2  Peter      Finance

In [29]:
table.iat[2, 2]

'Finance'

In [30]:
table.iloc[1:3, 0:3]

Name  Year      Program
1   Mary     2  Mathematics
2  Peter     1      Finance

In [31]:
table.iloc[1:3, [0, 2]]

Name      Program
1   Mary  Mathematics
2  Peter      Finance

In [32]:
table[table["Year"]>1]

Name  Year      Program
1  Mary     2  Mathematics
3  Jane     3      English

## Introduction to SciPy

In [33]:
import scipy
scipy.version.version

'1.6.2'